#!/usr/bin/env python3
"""Build S14 Table and S2 Fig. from saved aggregate sensitivity estimates.

This script typesets existing results only. It never loads participant data,
reruns models, or uses the additional random-assignment scenario intervals.
Run from any directory with: python3 build_setting_reassignment_si.py
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.colors import TwoSlopeNorm
from matplotlib.patches import Rectangle
import numpy as np


CONTRASTS = ("Outpatient vs control", "Acute vs control", "Acute vs outpatient")
PLOT_STEM = "figure_s2_setting_reassignment_plot"
REFERENCE_Q = 385 / 2512


def load_results(directory: Path):
    source = directory / "setting_reassignment_sensitivity"
    metadata = json.loads((source / "setting_reassignment_metadata.json").read_text())
    with (source / "setting_reassignment_summary.csv").open(newline="") as stream:
        rows = list(csv.DictReader(stream))
    if len(rows) != 126 or metadata["scenario_count"] != 42:
        raise ValueError("Expected 42 scenarios and three contrasts per scenario.")
    if metadata["bootstrap_successful"] != 2000 or metadata["bootstrap_failed"] != 0:
        raise ValueError("The approved analysis used 2,000 successful bootstrap samples.")
    expected_counts = {
        "known_n": 8292, "missing_setting_n": 455,
        "other_unknown_excluded_n": 148, "sensitivity_n": 8747,
    }
    if any(metadata[key] != value for key, value in expected_counts.items()):
        raise ValueError("Cohort counts differ from the approved sensitivity analysis.")
    groups = {}
    numeric = ("acute_fraction", "allocation_OR_per_steps_SD", "OR",
               "sampling_lower", "sampling_upper")
    for row in rows:
        for key in numeric:
            row[key] = float(row[key])
        if int(row["n"]) != 8747 or row["contrast"] not in CONTRASTS:
            raise ValueError("Unexpected sample size or contrast.")
        if not all(math.isfinite(row[key]) for key in numeric):
            raise ValueError("Nonfinite table estimate.")
        if not 0 < row["sampling_lower"] <= row["sampling_upper"]:
            raise ValueError("Invalid sampling interval.")
        scenario = groups.setdefault(row["scenario_id"], {})
        if row["contrast"] in scenario:
            raise ValueError("Duplicate scenario/contrast row.")
        scenario[row["contrast"]] = row
    for scenario in groups.values():
        if set(scenario) != set(CONTRASTS):
            raise ValueError("A scenario does not contain all three contrasts.")
        if not math.isclose(scenario[CONTRASTS[2]]["OR"],
                            scenario[CONTRASTS[1]]["OR"] / scenario[CONTRASTS[0]]["OR"],
                            rel_tol=1e-10):
            raise ValueError("The multinomial contrast identity does not reconcile.")
    return sorted(groups.values(), key=lambda scenario: (
        scenario[CONTRASTS[0]]["acute_fraction"],
        scenario[CONTRASTS[0]]["allocation_OR_per_steps_SD"])), metadata


def interval(row, tex=True):
    dash = "--" if tex else "\u2013"
    return f'{row["OR"]:.3f} ({row["sampling_lower"]:.3f}{dash}{row["sampling_upper"]:.3f})'


def table_source(scenarios):
    table_rows = []
    previous_q = None
    for index, scenario in enumerate(scenarios):
        row = scenario[CONTRASTS[0]]
        q = row["acute_fraction"]
        if previous_q is not None and q != previous_q:
            table_rows.append(r"\addlinespace[2pt]")
        q_label = f"{q * 100:g}"
        if math.isclose(q, REFERENCE_Q):
            q_label = r"15.3$^{\dagger}$"
        elif q in (0, 1):
            q_label = str(int(q * 100))
        allocation = "---" if q in (0, 1) else f'{row["allocation_OR_per_steps_SD"]:g}'
        same_group_next = index + 1 < len(scenarios) and math.isclose(
            scenarios[index + 1][CONTRASTS[0]]["acute_fraction"], q)
        row_end = r" \\*" if same_group_next else r" \\"
        table_rows.append(" & ".join([q_label, allocation] + [
            interval(scenario[contrast]) for contrast in CONTRASTS]) + row_end)
        previous_q = q
    return r"""% Generated by build_setting_reassignment_si.py from aggregate CSV outputs.
% No participant data or models are read/run by this typesetting source.
\documentclass[11pt]{article}
\usepackage[margin=0.65in]{geometry}
\usepackage[T1]{fontenc}
\usepackage{amsmath,booktabs,longtable,array,microtype}
\setlength{\parindent}{0pt}
\setlength{\parskip}{0.5em}
\begin{document}
\section*{S14 Table. Sensitivity to hypothetical allocation of missing CVD recording settings}

All values are Steps odds ratios (ORs) per 1 original pooled SD, with
scenario-conditional participant-bootstrap 95\% confidence intervals (CIs).
The two left columns specify assumptions about the 455 missing-setting cases,
not estimates of their true settings. Full methods are provided in S1 Text,
\textit{Missing-setting allocation sensitivity}.

{\small\setlength{\tabcolsep}{5pt}\renewcommand{\arraystretch}{1.13}
\begin{longtable}{@{}rrccc@{}}
\toprule
\shortstack{Assumed acute\\fraction $q$, \%} &
\shortstack{Allocation\\OR $e^{\lambda}$} &
\shortstack{Outpatient\\vs control} &
\shortstack{Acute care\\vs control} &
\shortstack{Acute care\\vs outpatient} \\
\midrule
\endfirsthead
\multicolumn{5}{@{}l}{\textit{S14 Table (continued)}} \\
\toprule
\shortstack{Assumed acute\\fraction $q$, \%} &
\shortstack{Allocation\\OR $e^{\lambda}$} &
\shortstack{Outpatient\\vs control} &
\shortstack{Acute care\\vs control} &
\shortstack{Acute care\\vs outpatient} \\
\midrule
\endhead
\midrule
\multicolumn{5}{r@{}}{\textit{Continued on next page}} \\
\endfoot
\bottomrule
\endlastfoot
""" + "\n".join(table_rows) + r"""
\end{longtable}}

{\footnotesize
Each scenario included 8747 participants: the original 8292 M1 participants
(5780 controls, 2127 outpatient and 385 acute-care cases) plus 455 cases with
missing settings. The 148 cases labelled Other/Unknown remained excluded.
The adjustment variables (age, sex, smoking frequency and drinking frequency)
and original Steps standardisation (SD 3298.82 steps/day) were unchanged.

For each missing-setting case, the hypothetical acute probability was
$p_i=\operatorname{logit}^{-1}(a+\lambda\mathrm{Steps}_{z,i})$; $a$ was calibrated
so the mean $p_i$ equalled $q$. Allocation OR $e^{\lambda}$ describes how these
\emph{assumed allocation odds} change per 1-SD higher Steps; it is distinct
from the fitted Steps ORs in the three right columns. An allocation OR of 1
sets equal acute probabilities for all missing-setting cases. Fractional
outcome contributions $(0,1-p_i,p_i)$ were used to maximise the expected
complete-data multinomial log-likelihood.

CIs are percentile intervals from 2000 participant-bootstrap samples, with
recalibration and refitting in each sample, conditional on each fixed
$(q,\lambda)$ pair. They do not incorporate uncertainty about which allocation
assumption is correct, and are not simultaneous intervals across scenarios.
$^{\dagger}$The fixed reference $q=385/2512$ (15.3\% when rounded) is the acute
fraction among known-setting cases, not an estimate for missing-setting cases.
At $q=0$ or $q=1$, every missing-setting case is assigned outpatient or acute
care, respectively; $\lambda$ is then irrelevant. These endpoint scenarios
are not mathematical bounds on the fitted association. Scenarios do not
recover individual settings, identify the missingness mechanism, or resolve
residual confounding. Values are rounded to three decimal places; PCA and
mediation models were not re-estimated. SD=standard deviation.
\par}
\end{document}
"""


def make_figure(scenarios, directory):
    rows = [scenario[CONTRASTS[2]] for scenario in scenarios]
    grid = [row for row in rows if 0 < row["acute_fraction"] < 1]
    qs = sorted({row["acute_fraction"] for row in grid})
    allocations = sorted({row["allocation_OR_per_steps_SD"] for row in grid})
    lookup = {(row["acute_fraction"], row["allocation_OR_per_steps_SD"]): row for row in grid}
    values = np.array([[lookup[q, allocation]["OR"] for allocation in allocations] for q in qs])
    plt.rcParams.update({"font.family": "DejaVu Sans", "font.size": 11,
                         "pdf.fonttype": 42, "ps.fonttype": 42})
    fig = plt.figure(figsize=(10.6, 8.6), facecolor="white")
    ax = fig.add_axes([0.155, 0.24, 0.725, 0.615])
    span = float(np.abs(np.log(values)).max())
    norm = TwoSlopeNorm(vmin=-span, vcenter=0, vmax=span)
    cmap = plt.get_cmap("RdBu_r")
    im = ax.imshow(np.log(values), cmap=cmap, norm=norm, aspect="auto")
    ax.set_xticks(range(len(allocations)), [f"{value:g}" for value in allocations])
    q_labels = ["15.3%" if math.isclose(q, REFERENCE_Q) else f"{q * 100:g}%" for q in qs]
    ax.set_yticks(range(len(qs)), q_labels)
    ax.tick_params(axis="both", length=0, pad=9, labelsize=11)
    ax.set_xlabel("Assumed allocation OR per 1-SD higher Steps", labelpad=12, fontsize=12)
    ax.set_ylabel("Assumed acute fraction among missing-setting cases", labelpad=10, fontsize=12)
    ax.set_xticks(np.arange(-0.5, len(allocations), 1), minor=True)
    ax.set_yticks(np.arange(-0.5, len(qs), 1), minor=True)
    ax.grid(which="minor", color="white", linewidth=1.5)
    ax.tick_params(which="minor", bottom=False, left=False)
    for spine in ax.spines.values():
        spine.set_visible(False)
    for i, q in enumerate(qs):
        for j, allocation in enumerate(allocations):
            row = lookup[q, allocation]
            rgb = cmap(norm(math.log(row["OR"])))[:3]
            luminance = sum(coefficient * value for coefficient, value in zip((0.2126, 0.7152, 0.0722), rgb))
            color = "white" if luminance < 0.48 else "#152536"
            ax.text(j, i - 0.12, f'{row["OR"]:.3f}', ha="center", va="center",
                    color=color, fontsize=12.8, fontweight="bold")
            ax.text(j, i + 0.20,
                    f'({row["sampling_lower"]:.3f}\u2013{row["sampling_upper"]:.3f})',
                    ha="center", va="center", color=color, fontsize=10)
    reference_row = min(range(len(qs)), key=lambda i: abs(qs[i] - REFERENCE_Q))
    reference_col = allocations.index(1.0)
    ax.add_patch(Rectangle((reference_col - .48, reference_row - .48), .96, .96,
                           fill=False, edgecolor="#182332", linewidth=1.5))
    cax = fig.add_axes([.90, .24, .023, .615])
    ticks = np.log([.6, .8, 1., 1.2, 1.6])
    cbar = fig.colorbar(im, cax=cax, ticks=ticks)
    cbar.ax.set_yticklabels(["0.6", "0.8", "1.0", "1.2", "1.6"])
    cbar.set_label("Fitted Steps OR (log colour scale)", labelpad=11)
    cbar.outline.set_visible(False)
    fig.text(.155, .947, "Acute-care versus outpatient recording", fontsize=17, fontweight="bold")
    fig.text(.155, .907, "Hypothetical settings for 455 cases; M1 covariates and Steps scale unchanged",
             fontsize=11.5, color="#435063")
    endpoint_rows = {row["scenario_id"]: row for row in rows if row["acute_fraction"] in (0, 1)}
    fig.text(.155, .117,
             "All 455 outpatient: " + interval(endpoint_rows["all_outpatient"], tex=False),
             fontsize=11.5, color="#152536")
    fig.text(.155, .076,
             "All 455 acute care: " + interval(endpoint_rows["all_acute"], tex=False),
             fontsize=11.5, color="#152536")
    fig.text(.155, .027, "Cells: fitted Steps OR (scenario-conditional bootstrap 95% CI); N = 8,747.",
             fontsize=10.5, color="#435063")
    fig.savefig(directory / f"{PLOT_STEM}.pdf", metadata={"Title": "S2 Figure: Missing-setting allocation sensitivity"})
    fig.savefig(directory / f"{PLOT_STEM}.png", dpi=200)
    plt.close(fig)


def figure_source():
    return r"""% Generated by build_setting_reassignment_si.py from saved aggregate outputs.
\documentclass[11pt]{article}
\usepackage[margin=0.7in]{geometry}
\usepackage[T1]{fontenc}
\usepackage{graphicx,microtype}
\setlength{\parindent}{0pt}
\begin{document}
\begin{center}
\includegraphics[width=\linewidth]{figure_s2_setting_reassignment_plot.pdf}
\end{center}
{\small
\textbf{S2 Fig. Sensitivity of the Steps association with CVD recording setting
to hypothetical allocation of missing settings.}
Cells report the acute-care-versus-outpatient Steps OR per 1 original pooled SD
(3298.82 steps/day), with scenario-conditional 95\% CIs from 2000 participant
bootstrap samples. The 455 missing-setting cases were added to the original
8292 participants; 148 Other/Unknown cases remained excluded. Row and column
values specify the assumed mean acute probability and its association with
Steps among missing-setting cases. Allocation ORs below (above) 1 favour acute
allocation at lower (higher) Steps; this assumption is distinct from the fitted
Steps OR displayed inside each cell. The outlined reference scenario uses
$q=385/2512$ (15.3\%), the known-setting acute fraction, and an allocation OR
of 1. Colours represent fitted Steps ORs on a log scale, centred at 1; no
significance threshold is encoded. All-outpatient and all-acute scenarios
are shown below the grid and are not mathematical bounds. CIs condition on
fixed allocation assumptions; these scenarios do not recover true settings
or resolve confounding. Full methods and all three outcome contrasts appear
in S1 Text and S14 Table. CI=confidence interval; OR=odds ratio;
SD=standard deviation.
\par}
\end{document}
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--directory", type=Path, default=Path(__file__).resolve().parent)
    args = parser.parse_args()
    directory = args.directory.resolve()
    scenarios, metadata = load_results(directory)
    (directory / "S14_Table.tex").write_text(table_source(scenarios))
    make_figure(scenarios, directory)
    (directory / "S2_Figure_setting_reassignment.tex").write_text(figure_source())
    print(f"Built S14 Table and S2 Fig. from {len(scenarios)} scenarios; "
          f'{metadata["bootstrap_successful"]} bootstrap samples; no models rerun.')


if __name__ == "__main__":
    main()
