#!/usr/bin/env python3
"""Render pooled manuscript/SI numbers from one canonical mediation CSV.

Run after run_robustness_and_figure2.py. This does not fit any model or edit
the prose. The generated TeX is shared by the main table, S3 and S4.
"""

import csv
import hashlib
from pathlib import Path

BASE = Path(__file__).resolve().parent
SOURCE = BASE / "robustness_mediation_summary.csv"
EFFECTS = ("ACME", "ADE", "Total")
RAW = ("Control probability", "Outpatient probability", "Acute probability")
PAIRWISE = ("Outpatient vs control", "Acute vs control", "Acute vs outpatient")
VARIANTS = ("Primary PCA", "Equal-weight composite", "PCA with deduplicated lipid burden")
RAW_NAMES = ("Control", "Outpatient", "Acute")
PAIR_NAMES = ("OutpatientControl", "AcuteControl", "AcuteOutpatient")


def number(value):
    return rf"\ensuremath{{{float(value):.3f}}}"


def interval(row):
    return (f"{number(row['estimate_percentage_points'])} "
            f"({number(row['CI_lower_percentage_points'])} to "
            f"{number(row['CI_upper_percentage_points'])})")


def p_value(row):
    p = float(row["p_value"])
    return r"\ensuremath{<0.001}" if p < 0.001 else f"{p:.3f}"


def main():
    with SOURCE.open() as handle:
        rows = list(csv.DictReader(handle))
    indexed = {(r["variant"], r["scale"], r["target"], r["effect"]): r
               for r in rows}
    if len(indexed) != len(rows):
        raise ValueError("Duplicate canonical summary rows.")

    def get(variant, scale, target, effect):
        r = indexed[(variant, scale, target, effect)]
        if int(r["successful_bootstrap"]) != 2000:
            raise ValueError("Manuscript output requires 2000 successful draws.")
        return r

    # A canonical primary export must match the robustness primary exactly.
    with (BASE / "mediation_bootstrap_summary.csv").open() as handle:
        primary_rows = list(csv.DictReader(handle))
    for r in primary_rows:
        reference = get("Primary PCA", "Pairwise-normalized", r["contrast"], r["effect"])
        for field in ("estimate", "CI_lower", "CI_upper", "p_value"):
            if float(r[field]) != float(reference[field]):
                raise ValueError(f"Noncanonical primary output: {r['contrast']} {field}")

    sha = hashlib.sha256(SOURCE.read_bytes()).hexdigest()
    text = ["% Generated by render_pooled_mediation_tex.py; do not hand-edit.",
            f"% Canonical source SHA256: {sha}"]
    for scale, targets, labels, prefix in (
        ("Raw category probability", RAW, RAW_NAMES, "Raw"),
        ("Pairwise-normalized", PAIRWISE, PAIR_NAMES, "Pair"),
    ):
        for target, label in zip(targets, labels):
            for effect in EFFECTS:
                r = get("Primary PCA", scale, target, effect)
                macro = f"Med{prefix}{label}{effect}"
                for suffix, value in (("Estimate", number(r["estimate_percentage_points"])),
                                      ("Interval", interval(r)), ("P", p_value(r))):
                    text.append(rf"\newcommand{{\{macro}{suffix}}}{{{value}}}")

    raw_rows = []
    for target, label in zip(RAW, ("Control", "Outpatient", "Acute care")):
        entries = [interval(get("Primary PCA", "Raw category probability", target, e))
                   for e in EFFECTS]
        raw_rows.append(" & ".join([label] + entries) + r" \\")
    text.append("\\newcommand{\\PrimaryRawMediationRows}{%\n" + "\n".join(raw_rows) + "\n}")

    pair_rows = []
    for target in PAIRWISE:
        entries = []
        for effect in EFFECTS:
            r = get("Primary PCA", "Pairwise-normalized", target, effect)
            entries.extend([interval(r), p_value(r)])
        pair_rows.append(" & ".join([target] + entries) + r" \\")
    text.append("\\newcommand{\\PrimaryPairwiseMediationRows}{%\n" + "\n".join(pair_rows) + "\n}")

    robust_rows = []
    for i, variant in enumerate(VARIANTS):
        if i:
            robust_rows.append(r"\addlinespace")
        label = ("Primary pooled PCA", "Equal-weight standardised composite",
                 "PCA with one combined lipid indicator")[i]
        for target in PAIRWISE:
            r = get(variant, "Pairwise-normalized", target, "ACME")
            robust_rows.append(" & ".join([label, target, interval(r)]) + r" \\")
    text.append("\\newcommand{\\RobustnessMediationRows}{%\n" + "\n".join(robust_rows) + "\n}")
    destination = BASE / "pooled_mediation_generated.tex"
    destination.write_text("\n".join(text) + "\n")
    print(f"Rendered canonical pooled estimates to {destination.name}; SHA256={sha}")


if __name__ == "__main__":
    main()
